name: common_configs
description: Common configs that can be shared as global configs in the application or with dart libraries.
version: 0.2.0
repository: https://github.com/predatorx7/common_configs
issue_tracker: https://github.com/predatorx7/common_configs/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
