name: common_configs
description: Common configs that can be shared as global configs in the application or with dart libraries.
version: 0.1.0
repository: https://github.com/predatorx7/flutter_packages.git

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
